In [4]:
# numpy 시간
# for, while, np의 시간을 알려줌

import time
import numpy as np

def calculate_sum_for_loop(n):
    start_time = time.time()
    total = 0
    for i in range(1, n+1):
        total += i
    end_time = time.time()
    return total, end_time-start_time
    

def calculate_sum_while_loop(n):
    start_time = time.time()
    total = 0
    i = 1 
    while i<=n :
        total += i
        i += 1
    end_time = time.time()
    return total, end_time-start_time
    
def calculate_sum_np_loop(n):
    start_time = time.time()
    numbers = np.arange(1, n+1) #1부터 n-1 전까지를 array로 만들어줌
    total = np.sum(numbers) 
    end_time = time.time()
    return total, end_time-start_time   

In [10]:
# 가능하면 loop를 피하는게 좋음 왜냐면 속도가 느려
n = int(input("정수를 입력하세요: "))
print()

result_for_loop, time_for_loop = calculate_sum_for_loop(1000000)
print("for: ", result_for_loop, time_for_loop)

result_for_loop, time_for_loop = calculate_sum_for_loop(1000000)
print("while: " ,result_for_loop, time_for_loop)

result_for_loop, time_for_loop = calculate_sum_for_loop(1000000)
print("np: ", result_for_loop, time_for_loop)

정수를 입력하세요: 100000

for:  500000500000 0.052227020263671875
while:  500000500000 0.029460906982421875
np:  500000500000 0.020748138427734375


In [6]:
# list
my_list = list(range(1,11))
print(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
#list내에서 홀수만 가져오기
odd_numbers = [x for x in my_list if x %2 !=0]
print(odd_numbers)



[1, 3, 5, 7, 9]

In [11]:
# 특정 조건만 가져오기
print(my_list[my_list>3])
# 그냥 리스트 object 내에서 조건 못함 np.array 써야함

TypeError: '>' not supported between instances of 'list' and 'int'

In [17]:
#특정 조건만 가져오기
import numpy as np

my_list = np.array([1,2,3,4,5,6,7,8,9,10]) #np로 만든 array의 경우 특정 조건을 줄 수 있음
numbers_greater_than_3 = my_list[my_list>3]
print(numbers_greater_than_3)

aa = my_list[(my_list>=5)&(my_list<=7)]
print(aa)

[ 4  5  6  7  8  9 10]
[5 6 7]


In [24]:
#list
my_list = list(range(1,15,3))
print(my_list)
my_list.append(17)
print(my_list)
my_list.insert(1, 1.5)
print(my_list)
my_list.remove(10)
print(my_list)
bottom = my_list.pop() #맨 뒤에 있는거 뽑아냄
print(my_list, bottom)
list1 = list(range(1,3))
my_list.extend(list1)
print(my_list)
list2 = my_list.copy()
print(list2)
list2.sort()
print(list2)
aa = list2.count(4)
print(aa)
list2.reverse()
print(list2)

[1, 4, 7, 10, 13]
[1, 4, 7, 10, 13, 17]
[1, 1.5, 4, 7, 10, 13, 17]
[1, 1.5, 4, 7, 13, 17]
[1, 1.5, 4, 7, 13] 17
[1, 1.5, 4, 7, 13, 1, 2]
[1, 1.5, 4, 7, 13, 1, 2]
[1, 1, 1.5, 2, 4, 7, 13]
1
[13, 7, 4, 2, 1.5, 1, 1]


In [27]:
import numpy as np

sample_array = np.array([1,2,3,4,5])
print(sample_array)

sample_array2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(sample_array2)

[1 2 3 4 5]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [29]:
print(sample_array.shape)
print(sample_array.ndim)

print(sample_array2.shape)
print(sample_array2.ndim)

(5,)
1
(2, 5)
2


In [30]:
a2 = np.arange(20)
print(a2)
#reshape를 사용해 for문 없이 array 만들 수 o
print(a2.reshape(4,-1)) #20 = 4x5(-1)
print(a2.reshape(2,5, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [34]:
#np.zeros((x,y)), np.ones(x)
print(np.zeros((10))) #10행 1열
print(np.zeros((10,3))) #10행 3열
print(np.ones((2, 10))) #2행 10열
print(np.ones(1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[1.]


In [41]:
a2= a2.reshape(4,-1)
print(a2)
print()
print(a2[2:4])
print(a2[1, 2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[[10 11 12 13 14]
 [15 16 17 18 19]]
[7 8 9]


In [45]:
arr = np.array([1.0,2.0,3.0, 4.0, 5.0, 6])
print(arr)
arr = arr.reshape(2,-1)
print(arr)

[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [4. 5. 6.]]


In [65]:
#벡터화(vectorization)
print(arr.dtype)
print(arr)
print(arr*arr) #곱하기
print(arr-arr) #빼기
print(1/arr) #나누기
#브로캐스팅: 크기가 다른 배열 간 연산 가능, 단 차원의 길이가 같은 경우만 가능
arr2 = np.array([[2,2,3]])
print(arr+arr2)

float64
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[3. 4. 6.]
 [6. 7. 9.]]


# Series와 DataFrame

In [80]:
#pandas, numpy
import pandas as pd
import numpy as np

# series
mys = pd.Series([1,2,4,8,16,32])
print(mys)
print()


print(mys.index)
print(mys.values)
print(mys.shape)

0     1
1     2
2     4
3     8
4    16
5    32
dtype: int64

RangeIndex(start=0, stop=6, step=1)
[ 1  2  4  8 16 32]
(6,)


In [81]:
# df = pd.DataFrame(data, index=index, columns=columns)

# dataframe 만들기 (List, Dictionary, Array로 만들 수 있음, 배열이나 리스트가 보편적)
#리스트로 만들기 
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [82]:
#딕셔너리로 만들기
data = {"age":[20, 40], 
       "height": [180, 173],
       "weight": [50, 60]}
index_name = ["A", "B"]
df2 = pd.DataFrame(data, index=index_name)
df2

age  height  weight
A   20     180      50
B   40     173      60

In [83]:
#array로 만들기
array1 = np.array([1,2,3,4,5])
df3 = pd.DataFrame({"col1": array1, "col2": array1*2, "col3": ["a", "b", "c", "d", "e"]})
df3

col1  col2 col3
0     1     2    a
1     2     4    b
2     3     6    c
3     4     8    d
4     5    10    e

In [84]:
np.random.seed(22)

df = pd.DataFrame(np.random.randint(1,10, size=(3,5)))
df

#난수 생성 : 
#np.random.rand: 0부터 1사이 균일 분포
#np.random.randn: 가우시안 표준 정규분포 
#np.random.randint: 균일 분포의 정수 난수 (np.random.randint(low, high, size))

0  1  2  3  4
0  6  5  1  5  7
1  7  5  9  5  3
2  9  8  3  9  9

In [98]:
np.random.seed(1886)
df=pd.DataFrame(np.random.randint(10,22,(4,5)), index = ["a", "b", "c", "d"], columns=["A", "B", "C", "D", "E"])
print(df)
print()
print(df.index)
print(df.columns)
print(df.values)
print(df.shape)

    A   B   C   D   E
a  16  13  11  19  18
b  14  14  13  15  17
c  20  13  18  20  16
d  18  21  16  13  21

Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
[[16 13 11 19 18]
 [14 14 13 15 17]
 [20 13 18 20 16]
 [18 21 16 13 21]]
(4, 5)


In [88]:
print(df.head(2))

    A   B   C   D   E
a  16  13  11  19  18
b  14  14  13  15  17


In [89]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
 3   D       4 non-null      int64
 4   E       4 non-null      int64
dtypes: int64(5)
memory usage: 192.0+ bytes
None


In [91]:
df.shape

(4, 5)

In [93]:
df["A"] #colum명이 A인 애

a    16
b    14
c    20
d    18
Name: A, dtype: int64

In [96]:
df[["A", "C"]]

A   C
a  16  11
b  14  13
c  20  18
d  18  16

In [109]:
df[df["A"]>16] #조건문으로 데이터 추출

A   B   C   D   E
c  20  13  18  20  16
d  18  21  16  13  21

In [112]:
df.query('index=="a"') #index로 특정 행 추출

A   B   C   D   E
a  16  13  11  19  18

In [113]:
df.drop("A", axis =1) #지정한 열 빼고 데이터 추출

B   C   D   E
a  13  11  19  18
b  14  13  15  17
c  13  18  20  16
d  21  16  13  21

In [114]:
df.loc["a"] #특정 이름을 가진 행 추출

A    16
B    13
C    11
D    19
E    18
Name: a, dtype: int64

In [115]:
df["b":"c"]

A   B   C   D   E
b  14  14  13  15  17
c  20  13  18  20  16

In [116]:
df.loc["a", :"d"]

A    16
B    13
C    11
D    19
E    18
Name: a, dtype: int64

In [117]:
df.loc[df.A>15]

A   B   C   D   E
a  16  13  11  19  18
c  20  13  18  20  16
d  18  21  16  13  21

In [123]:
df.loc["a","B"]

13

In [124]:
df.loc[["a","b"], "C":"E"]

C   D   E
a  11  19  18
b  13  15  17

In [125]:
df.iloc[2]

A    20
B    13
C    18
D    20
E    16
Name: c, dtype: int64

In [126]:
df.iloc[:2, 2]

a    11
b    13
Name: C, dtype: int64

In [130]:
print(df.count(axis=0)) #axis=0은 컬럼기준
print(df.count(axis=1)) #axis=1은 로우기준
print(df.dtypes) #dtypes: 데이터 형태
print(df.describe) #요약통계량

A    4
B    4
C    4
D    4
E    4
dtype: int64
a    5
b    5
c    5
d    5
dtype: int64
A    int64
B    int64
C    int64
D    int64
E    int64
dtype: object
<bound method NDFrame.describe of     A   B   C   D   E
a  16  13  11  19  18
b  14  14  13  15  17
c  20  13  18  20  16
d  18  21  16  13  21>


# File

%%는 셀매직 명령어, %는 line매직 명령어
CSV: Comma Seperate Value, ","로 구분된 파일

In [137]:
%%writefile sample1.csv 
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Overwriting sample1.csv


In [147]:
%pwd
#pd.read_csv("파일명")
data = pd.read_csv("./sample1.csv")
print(data)
print()

print(data.head(1))
print()

print(data.shape)

   c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

   c1    c2    c3
0   1  1.11   one

(3, 3)
